version: "3"
services:
  frontend:
    image: pexels-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`pexels.localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
  backend:
    image: pexels-backend
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    ports:
      - 3000
    volumes:
      - ./backend/src:/app/src
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=(Host(`pexels.localhost`) && PathPrefix(`/api`))"
      - "traefik.http.routers.backend.entrypoints=web"
  load-balancer:
    image: traefik:v2.2
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
